# Generated by Django 5.0.2 on 2024-03-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_management', '0002_register_location_alter_register_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(default='', max_length=50)),
                ('measurement', models.IntegerField(null=True)),
                ('style_preference', models.CharField(default='', max_length=50)),
                ('fit_preference', models.CharField(default='', max_length=50)),
                ('purpose_of_the_garment', models.IntegerField(null=True)),
                ('timeline', models.URLField(null=True)),
                ('image', models.FileField(null=True, upload_to='id_proof/')),
                ('cost', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
